name: CI/CD Pipeline for Java App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.1
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t my-java-app:latest .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Cambia a tu región de AWS

      - name: Log in to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag Docker image
        run: |
          IMAGE_URI="${{ steps.ecr_login.outputs.registry }}/my-java-app:latest"
          docker tag my-java-app:latest $IMAGE_URI

      - name: Push Docker image to Amazon ECR
        run: |
          IMAGE_URI="${{ steps.ecr_login.outputs.registry }}/my-java-app:latest"
          docker push $IMAGE_URI

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: my-ecs-cluster
          service: my-ecs-service
          image: ${{ steps.ecr_login.outputs.registry }}/my-java-app:latest
          region: us-west-2  # Cambia a tu región de AWS

